// Generated by CoffeeScript 1.3.1
(function() {
  var Checker, GenericChecker, schemas, schemasForJSON,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  Checker = require('./checker').Checker;

  schemas = require('./genericSchemas').schemas;

  schemasForJSON = require('./genericSchemas').schemasForJSON;

  GenericChecker = (function(_super) {

    __extends(GenericChecker, _super);

    GenericChecker.name = 'GenericChecker';

    function GenericChecker(log) {
      GenericChecker.__super__.constructor.apply(this, arguments);
    }

    GenericChecker.prototype.getSchema = function(schemaID, forJSON) {
      if (forJSON == null) {
        forJSON = false;
      }
      if (forJSON) {
        return schemasForJSON[schemaID];
      } else {
        return schemas[schemaID];
      }
    };

    return GenericChecker;

  })(Checker);

  exports.GenericChecker = GenericChecker;

}).call(this);
