// Generated by CoffeeScript 1.3.3
(function() {
  var codeCur, codeListCur, componentCur, conceptCur, conceptSchemeCur, dataStructureCur, dimensionPos, entryActions, exitActions, guards, header, sdmx, util, _;

  _ = require('underscore');

  header = require('./header');

  sdmx = require('../../pipe/sdmxPipe');

  util = require('../../util/util');

  codeListCur = {};

  codeCur = {};

  conceptSchemeCur = {};

  conceptCur = {};

  dataStructureCur = {};

  componentCur = {};

  dimensionPos = 0;

  entryActions = {
    'Structures/Codelists': function(attrs) {},
    'Structures/Codelists/Codelist': function(attrs) {
      codeListCur = _.extend({}, attrs);
      if (codeListCur.isPartial != null) {
        return codeListCur.isPartial = codeListCur.isPartial === 'true';
      }
    },
    'Structures/Codelists/Codelist/Code': function(attrs) {
      return codeCur = _.extend({}, attrs);
    },
    'Structures/Concepts/ConceptScheme': function(attrs) {
      conceptSchemeCur = _.extend({}, attrs);
      if (conceptSchemeCur.isPartial != null) {
        return conceptSchemeCur.isPartial = conceptSchemeCur.isPartial === 'true';
      }
    },
    'Structures/Concepts/ConceptScheme/Concept': function(attrs) {
      return conceptCur = _.extend({}, attrs);
    },
    'Structures/Concepts/ConceptScheme/Concept/CoreRepresentation/TextFormat': function(attrs) {
      var _ref;
      if ((_ref = conceptCur.coreRepresentation) == null) {
        conceptCur.coreRepresentation = {};
      }
      return conceptCur.coreRepresentation.textFormat = attrs;
    },
    'Structures/DataStructures/DataStructure': function(attrs) {
      dataStructureCur = _.extend({}, attrs);
      return dimensionPos = 0;
    },
    'Structures/DataStructures/DataStructure/DataStructureComponents/DimensionList/Dimension': function(attrs) {
      componentCur = _.extend({}, attrs);
      dimensionPos += 1;
      componentCur.order = dimensionPos;
      return componentCur.type = 'dimension';
    },
    'Structures/DataStructures/DataStructure/DataStructureComponents/DimensionList/Dimension/ConceptIdentity/Ref': function(attrs) {
      var _base, _ref, _ref1;
      if ((_ref = componentCur.conceptIdentity) == null) {
        componentCur.conceptIdentity = {};
      }
      return (_ref1 = (_base = componentCur.conceptIdentity).ref) != null ? _ref1 : _base.ref = _.extend({}, attrs);
    },
    'Structures/DataStructures/DataStructure/DataStructureComponents/DimensionList/TimeDimension': function(attrs) {
      componentCur = _.extend({}, attrs);
      dimensionPos += 1;
      componentCur.order = dimensionPos;
      return componentCur.type = 'timeDimension';
    },
    'Structures/DataStructures/DataStructure/DataStructureComponents/DimensionList/TimeDimension/ConceptIdentity/Ref': function(attrs) {
      var _base, _ref, _ref1;
      if ((_ref = componentCur.conceptIdentity) == null) {
        componentCur.conceptIdentity = {};
      }
      return (_ref1 = (_base = componentCur.conceptIdentity).ref) != null ? _ref1 : _base.ref = _.extend({}, attrs);
    },
    'Structures/DataStructures/DataStructure/DataStructureComponents/Group': function(attrs) {
      return componentCur = _.extend({}, attrs);
    },
    'Structures/DataStructures/DataStructure/DataStructureComponents/Group/GroupDimension/DimensionReference/Ref': function(attrs) {
      var _ref;
      if ((_ref = componentCur.dimension) == null) {
        componentCur.dimension = [];
      }
      return componentCur.dimension.push(attrs.id);
    },
    'Structures/DataStructures/DataStructure/DataStructureComponents/AttributeList/Attribute': function(attrs) {
      return componentCur = _.extend({}, attrs);
    },
    'Structures/DataStructures/DataStructure/DataStructureComponents/AttributeList/Attribute/ConceptIdentity/Ref': function(attrs) {
      var _base, _ref, _ref1;
      if ((_ref = componentCur.conceptIdentity) == null) {
        componentCur.conceptIdentity = {};
      }
      return (_ref1 = (_base = componentCur.conceptIdentity).ref) != null ? _ref1 : _base.ref = _.extend({}, attrs);
    },
    'Structures/DataStructures/DataStructure/DataStructureComponents/AttributeList/Attribute/AttributeRelationship/Dimension/Ref': function(attrs) {
      var _base, _ref, _ref1;
      if ((_ref = componentCur.attributeRelationship) == null) {
        componentCur.attributeRelationship = {};
      }
      if ((_ref1 = (_base = componentCur.attributeRelationship).dimension) == null) {
        _base.dimension = [];
      }
      return componentCur.attributeRelationship.dimension.push(attrs.id);
    },
    'Structures/DataStructures/DataStructure/DataStructureComponents/AttributeList/Attribute/AttributeRelationship/Group/Ref': function(attrs) {
      var _ref;
      if ((_ref = componentCur.attributeRelationship) == null) {
        componentCur.attributeRelationship = {};
      }
      return componentCur.attributeRelationship.group = attrs.id;
    },
    'Structures/DataStructures/DataStructure/DataStructureComponents/AttributeList/Attribute/AttributeRelationship/PrimaryMeasure/Ref': function(attrs) {
      var _ref;
      if ((_ref = componentCur.attributeRelationship) == null) {
        componentCur.attributeRelationship = {};
      }
      return componentCur.attributeRelationship.primaryMeasure = attrs.id;
    },
    'Structures/DataStructures/DataStructure/DataStructureComponents/MeasureList/PrimaryMeasure': function(attrs) {
      return componentCur = _.extend({}, attrs);
    },
    'Structures/DataStructures/DataStructure/DataStructureComponents/MeasureList/PrimaryMeasure/ConceptIdentity/Ref': function(attrs) {
      var _base, _ref, _ref1;
      if ((_ref = componentCur.conceptIdentity) == null) {
        componentCur.conceptIdentity = {};
      }
      return (_ref1 = (_base = componentCur.conceptIdentity).ref) != null ? _ref1 : _base.ref = _.extend({}, attrs);
    }
  };

  exitActions = {
    'Structures/Codelists/Codelist': function(attrs) {
      return this.emitSDMX(sdmx.CODE_LIST, codeListCur);
    },
    'Structures/Codelists/Codelist/Code': function(attrs) {
      var _ref;
      if ((_ref = codeListCur.codes) == null) {
        codeListCur.codes = {};
      }
      return codeListCur.codes[codeCur.id] = codeCur;
    },
    'Structures/Codelists/Codelist/Name': function(attrs) {
      var _ref, _ref1;
      if ((_ref = attrs['xml:lang']) == null) {
        attrs['xml:lang'] = 'en';
      }
      if ((_ref1 = codeListCur.name) == null) {
        codeListCur.name = {};
      }
      return codeListCur.name[attrs['xml:lang']] = this.stringBuffer;
    },
    'Structures/Codelists/Codelist/Description': function(attrs) {
      var _ref, _ref1;
      if ((_ref = attrs['xml:lang']) == null) {
        attrs['xml:lang'] = 'en';
      }
      if ((_ref1 = codeListCur.description) == null) {
        codeListCur.description = {};
      }
      return codeListCur.description[attrs['xml:lang']] = this.stringBuffer;
    },
    'Structures/Codelists/Codelist/Code/Name': function(attrs) {
      var _ref, _ref1;
      if ((_ref = attrs['xml:lang']) == null) {
        attrs['xml:lang'] = 'en';
      }
      if ((_ref1 = codeCur.name) == null) {
        codeCur.name = {};
      }
      return codeCur.name[attrs['xml:lang']] = this.stringBuffer;
    },
    'Structures/Codelists/Codelist/Code/Description': function(attrs) {
      var _ref, _ref1;
      if ((_ref = attrs['xml:lang']) == null) {
        attrs['xml:lang'] = 'en';
      }
      if ((_ref1 = codeCur.description) == null) {
        codeCur.description = {};
      }
      return codeCur.description[attrs['xml:lang']] = this.stringBuffer;
    },
    'Structures/Concepts/ConceptScheme': function(attrs) {
      return this.emitSDMX(sdmx.CONCEPT_SCHEME, conceptSchemeCur);
    },
    'Structures/Concepts/ConceptScheme/Name': function(attrs) {
      var _ref, _ref1;
      if ((_ref = attrs['xml:lang']) == null) {
        attrs['xml:lang'] = 'en';
      }
      if ((_ref1 = conceptSchemeCur.name) == null) {
        conceptSchemeCur.name = {};
      }
      return conceptSchemeCur.name[attrs['xml:lang']] = this.stringBuffer;
    },
    'Structures/Concepts/ConceptScheme/Concept': function() {
      var _ref;
      if ((_ref = conceptSchemeCur.concepts) == null) {
        conceptSchemeCur.concepts = {};
      }
      return conceptSchemeCur.concepts[conceptCur.id] = conceptCur;
    },
    'Structures/Concepts/ConceptScheme/Concept/Name': function(attrs) {
      var _ref, _ref1;
      if ((_ref = attrs['xml:lang']) == null) {
        attrs['xml:lang'] = 'en';
      }
      if ((_ref1 = conceptCur.name) == null) {
        conceptCur.name = {};
      }
      return conceptCur.name[attrs['xml:lang']] = this.stringBuffer;
    },
    'Structures/Concepts/ConceptScheme/Concept/Description': function(attrs) {
      var _ref, _ref1;
      if ((_ref = attrs['xml:lang']) == null) {
        attrs['xml:lang'] = 'en';
      }
      if ((_ref1 = conceptCur.description) == null) {
        conceptCur.description = {};
      }
      return conceptCur.description[attrs['xml:lang']] = this.stringBuffer;
    },
    'Structures/Concepts/ConceptScheme/Concept/CoreRepresentation/Enumeration/URN': function() {
      var _base, _ref, _ref1;
      if ((_ref = conceptCur.coreRepresentation) == null) {
        conceptCur.coreRepresentation = {};
      }
      if ((_ref1 = (_base = conceptCur.coreRepresentation).enumeration) == null) {
        _base.enumeration = {};
      }
      return conceptCur.coreRepresentation.enumeration.ref = this.parseURN(this.stringBuffer);
    },
    'Structures/DataStructures/DataStructure': function(attrs) {
      return this.emitSDMX(sdmx.DATA_STRUCTURE_DEFINITION, dataStructureCur);
    },
    'Structures/DataStructures/DataStructure/Name': function(attrs) {
      var _ref, _ref1;
      if ((_ref = attrs['xml:lang']) == null) {
        attrs['xml:lang'] = 'en';
      }
      if ((_ref1 = dataStructureCur.name) == null) {
        dataStructureCur.name = {};
      }
      return dataStructureCur.name[attrs['xml:lang']] = this.stringBuffer;
    },
    'Structures/DataStructures/DataStructure/DataStructureComponents/DimensionList/Dimension': function() {
      var _ref;
      if ((_ref = dataStructureCur.dimensionDescriptor) == null) {
        dataStructureCur.dimensionDescriptor = {};
      }
      return dataStructureCur.dimensionDescriptor[componentCur.id] = componentCur;
    },
    'Structures/DataStructures/DataStructure/DataStructureComponents/DimensionList/TimeDimension': function() {
      var _ref;
      if ((_ref = dataStructureCur.dimensionDescriptor) == null) {
        dataStructureCur.dimensionDescriptor = {};
      }
      return dataStructureCur.dimensionDescriptor[componentCur.id] = componentCur;
    },
    'Structures/DataStructures/DataStructure/DataStructureComponents/DimensionList/Dimension/ConceptIdentity/URN': function() {
      var _base, _ref, _ref1;
      if ((_ref = componentCur.conceptIdentity) == null) {
        componentCur.conceptIdentity = {};
      }
      return (_ref1 = (_base = componentCur.conceptIdentity).ref) != null ? _ref1 : _base.ref = this.parseURN(this.stringBuffer);
    },
    'Structures/DataStructures/DataStructure/DataStructureComponents/DimensionList/TimeDimension/ConceptIdentity/URN': function() {
      var _base, _ref, _ref1;
      if ((_ref = componentCur.conceptIdentity) == null) {
        componentCur.conceptIdentity = {};
      }
      return (_ref1 = (_base = componentCur.conceptIdentity).ref) != null ? _ref1 : _base.ref = this.parseURN(this.stringBuffer);
    },
    'Structures/DataStructures/DataStructure/DataStructureComponents/Group': function() {
      var _ref;
      if ((_ref = dataStructureCur.dimensionGroupDescriptor) == null) {
        dataStructureCur.dimensionGroupDescriptor = {};
      }
      return dataStructureCur.dimensionGroupDescriptor[componentCur.id] = componentCur;
    },
    'Structures/DataStructures/DataStructure/DataStructureComponents/AttributeList/Attribute': function() {
      var _ref;
      if ((_ref = dataStructureCur.attributeDescriptor) == null) {
        dataStructureCur.attributeDescriptor = {};
      }
      return dataStructureCur.attributeDescriptor[componentCur.id] = componentCur;
    },
    'Structures/DataStructures/DataStructure/DataStructureComponents/AttributeList/Attribute/ConceptIdentity/URN': function() {
      var _base, _ref, _ref1;
      if ((_ref = componentCur.conceptIdentity) == null) {
        componentCur.conceptIdentity = {};
      }
      return (_ref1 = (_base = componentCur.conceptIdentity).ref) != null ? _ref1 : _base.ref = this.parseURN(this.stringBuffer);
    },
    'Structures/DataStructures/DataStructure/DataStructureComponents/MeasureList/PrimaryMeasure': function() {
      var _ref;
      if ((_ref = dataStructureCur.measureDescriptor) == null) {
        dataStructureCur.measureDescriptor = {};
      }
      return dataStructureCur.measureDescriptor.primaryMeasure = componentCur;
    },
    'Structures/DataStructures/DataStructure/DataStructureComponents/MeasureList/PrimaryMeasure/ConceptIdentity/URN': function() {
      var _base, _ref, _ref1;
      if ((_ref = componentCur.conceptIdentity) == null) {
        componentCur.conceptIdentity = {};
      }
      if ((_ref1 = (_base = componentCur.conceptIdentity).ref) == null) {
        _base.ref = this.parseURN(this.stringBuffer);
      }
      return componentCur.id = componentCur.conceptIdentity.ref.id;
    }
  };

  guards = {};

  exports.fst = _.extend({}, header.fst, entryActions, exitActions, guards);

  exports.entryActions = _.defaults(entryActions, header.entryActions);

  exports.exitActions = _.defaults(exitActions, header.exitActions);

  exports.guards = _.defaults(guards, header.guards);

}).call(this);
