// Generated by CoffeeScript 1.3.1
(function() {
  var DebugPipe, SdmxPipe, util,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  SdmxPipe = require('../pipe/sdmxPipe').SdmxPipe;

  util = require('util');

  DebugPipe = (function(_super) {

    __extends(DebugPipe, _super);

    DebugPipe.name = 'DebugPipe';

    function DebugPipe(log) {
      DebugPipe.__super__.constructor.apply(this, arguments);
    }

    DebugPipe.prototype.processData = function(sdmxdata) {
      console.log(util.inspect(sdmxdata, true, null, true));
      return DebugPipe.__super__.processData.apply(this, arguments);
    };

    return DebugPipe;

  })(SdmxPipe);

  exports.DebugPipe = DebugPipe;

}).call(this);
