// Generated by CoffeeScript 1.3.1
(function() {
  var Stream, StringStream,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  Stream = require('stream').Stream;

  StringStream = (function(_super) {

    __extends(StringStream, _super);

    StringStream.name = 'StringStream';

    function StringStream(string) {
      this.string = string != null ? string : '';
      this.writable = true;
      this.readable = true;
    }

    StringStream.prototype.write = function(string) {
      this.string += string;
      this.emit('data', string);
      return true;
    };

    StringStream.prototype.end = function(string) {
      this.atEnd = true;
      if (string != null) {
        this.string += string;
      }
      this.writable = false;
      return this.emit('end');
    };

    StringStream.prototype.destroy = function() {
      return this.writable = false;
    };

    return StringStream;

  })(Stream);

  exports.StringStream = StringStream;

}).call(this);
