// Generated by CoffeeScript 1.3.1
(function() {
  var dataSetCur, entryActions, exitActions, groupCur, guards, header, sdmx, seriesCur, xmlns_gen, xmlns_msg, _;

  _ = require('underscore');

  header = require('./header');

  sdmx = require('../../pipe/sdmxPipe');

  xmlns_msg = 'http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message';

  xmlns_gen = 'http://www.SDMX.org/resources/SDMXML/schemas/v2_0/generic';

  dataSetCur = {};

  seriesCur = {};

  groupCur = {};

  entryActions = {
    'DataSet': function(attrs) {
      return dataSetCur = _.extend({}, attrs);
    },
    'DataSet/Group': function() {
      return groupCur = {
        type: 'SiblingGroup',
        groupKey: {},
        attributes: {}
      };
    },
    'DataSet/Group/GroupKey/Value': function(attrs) {
      return groupCur.groupKey[attrs.concept] = attrs.value;
    },
    'DataSet/Group/Attributes/Value': function(attrs) {
      return groupCur.attributes[attrs.concept] = attrs.value;
    },
    'DataSet/Group/Series': function() {
      return seriesCur = {
        seriesKey: {},
        attributes: {},
        obs: {
          obsDimension: [],
          obsValue: []
        }
      };
    },
    'DataSet/Group/Series/SeriesKey/Value': function(attrs) {
      return seriesCur.seriesKey[attrs.concept] = attrs.value;
    },
    'DataSet/Group/Series/Attributes/Value': function(attrs) {
      return seriesCur.attributes[attrs.concept] = attrs.value;
    },
    'DataSet/Group/Series/Obs/ObsValue': function(attrs) {
      return seriesCur.obs.obsValue.push(Number(attrs.value));
    },
    'DataSet/Group/Series/Obs/Attributes/Value': function(attrs) {
      var _base, _base1, _name;
      if ((_base = seriesCur.obs).attributes == null) {
        _base.attributes = {};
      }
      if ((_base1 = seriesCur.obs.attributes)[_name = attrs.concept] == null) {
        _base1[_name] = [];
      }
      return seriesCur.obs.attributes[attrs.concept].push(attrs.value);
    }
  };

  entryActions['DataSet/Series'] = entryActions['DataSet/Group/Series'];

  entryActions['DataSet/Series/SeriesKey/Value'] = entryActions['DataSet/Group/Series/SeriesKey/Value'];

  entryActions['DataSet/Series/Attributes/Value'] = entryActions['DataSet/Group/Series/Attributes/Value'];

  entryActions['DataSet/Series/Obs/ObsValue'] = entryActions['DataSet/Group/Series/Obs/ObsValue'];

  entryActions['DataSet/Series/Obs/Attributes/Value'] = entryActions['DataSet/Group/Series/Obs/Attributes/Value'];

  exitActions = {
    'DataSet/KeyFamilyRef': function() {
      dataSetCur.structureRef = this.stringBuffer;
      return this.emitSDMX(sdmx.DATA_SET_HEADER, dataSetCur);
    },
    'DataSet': function() {},
    'DataSet/Group': function() {
      return this.emitSDMX(sdmx.ATTRIBUTE_GROUP, groupCur);
    },
    'DataSet/Group/Series': function() {
      return this.emitSDMX(sdmx.SERIES, seriesCur);
    },
    'DataSet/Group/Series/Obs/Time': function() {
      return seriesCur.obs.obsDimension.push(this.stringBuffer);
    }
  };

  exitActions['DataSet/Series'] = exitActions['DataSet/Group/Series'];

  exitActions['DataSet/Series/Obs/Time'] = exitActions['DataSet/Group/Series/Obs/Time'];

  guards = {};

  exports.fst = _.extend({}, header.fst, entryActions, exitActions, guards);

  exports.entryActions = _.defaults(entryActions, header.entryActions);

  exports.exitActions = _.defaults(exitActions, header.exitActions);

  exports.guards = _.defaults(guards, header.guards);

}).call(this);
